# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: addd7c4d59b0b5ece3dfdd582d7006bbcb579a64f16719d46d1822ca87ed4d020fdc6ee5c4ccff9ee344035579024dd6d0dde31ee74fec8669062ec64977d56d

test:
  secret_key_base: e51767529d421296781e8a954473c6a49d3e8416b39ecccd3bd1ae2358e355270bb83f67da4cdf94f3bc59217ddc16208843320006c239b1951e07b621a1f59c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
